[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "coco_rs"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["numpy"]

[tool.maturin]
features = ["pyo3/extension-module"]
